# Generated by Django 6.0.4 on 2026-05-11 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='paciente',
            name='domicilio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.CharField(blank=True, choices=[('femenino', 'Femenino'), ('masculino', 'Masculino'), ('otro', 'Otro'), ('prefiere_no_decir', 'Prefiere no decir')], max_length=30),
        ),
        migrations.AddField(
            model_name='paciente',
            name='localidad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_afiliado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paciente',
            name='obra_social',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='FichaOdontologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes_medicos', models.TextField(blank=True)),
                ('alergias', models.TextField(blank=True)),
                ('medicacion_actual', models.TextField(blank=True)),
                ('enfermedades_relevantes', models.TextField(blank=True)),
                ('embarazo', models.CharField(blank=True, choices=[('', 'Sin datos'), ('si', 'Si'), ('no', 'No')], max_length=10)),
                ('hipertension', models.CharField(blank=True, choices=[('', 'Sin datos'), ('si', 'Si'), ('no', 'No')], max_length=10)),
                ('diabetes', models.CharField(blank=True, choices=[('', 'Sin datos'), ('si', 'Si'), ('no', 'No')], max_length=10)),
                ('problemas_cardiacos', models.CharField(blank=True, choices=[('', 'Sin datos'), ('si', 'Si'), ('no', 'No')], max_length=10)),
                ('observaciones_generales', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_odontologicas_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_odontologica', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Ficha odontologica',
                'verbose_name_plural': 'Fichas odontologicas',
            },
        ),
    ]
