# Generated by Django 6.0.4 on 2026-05-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_contacto_emergencia_paciente_domicilio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichaodontologica',
            options={'verbose_name': 'Ficha odontológica', 'verbose_name_plural': 'Fichas odontológicas'},
        ),
    ]
