# Generated by Django 6.0.4 on 2026-05-12 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def crear_asociaciones_desde_turnos(apps, schema_editor):
    PacienteOdontologo = apps.get_model('pacientes', 'PacienteOdontologo')
    Turno = apps.get_model('turnos', 'Turno')

    pares = (
        Turno.objects.order_by('paciente_id', 'odontologo_id')
        .values('paciente_id', 'odontologo_id')
        .distinct()
    )

    for par in pares:
        PacienteOdontologo.objects.get_or_create(
            paciente_id=par['paciente_id'],
            odontologo_id=par['odontologo_id'],
            activo=True,
            defaults={'motivo': 'Asociación inicial por turno existente'},
        )


def revertir_asociaciones_desde_turnos(apps, schema_editor):
    PacienteOdontologo = apps.get_model('pacientes', 'PacienteOdontologo')
    PacienteOdontologo.objects.filter(
        motivo='Asociación inicial por turno existente',
        asignado_por__isnull=True,
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_fichaodontologica_options'),
        ('turnos', '0008_alter_disponibilidadodontologo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteOdontologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_pacientes_odontologos', to=settings.AUTH_USER_MODEL)),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes_asociados', to='turnos.odontologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odontologos_asociados', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Asociación paciente-odontólogo',
                'verbose_name_plural': 'Asociaciones paciente-odontólogo',
                'ordering': ['paciente__apellido', 'paciente__nombre', 'odontologo'],
                'indexes': [models.Index(fields=['paciente', 'activo'], name='pacientes_p_pacient_556e34_idx'), models.Index(fields=['odontologo', 'activo'], name='pacientes_p_odontol_24303c_idx'), models.Index(fields=['paciente', 'odontologo', 'activo'], name='pacientes_p_pacient_2c4d6f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('paciente', 'odontologo'), name='uniq_paciente_odontologo_activo')],
            },
        ),
        migrations.RunPython(
            crear_asociaciones_desde_turnos,
            revertir_asociaciones_desde_turnos,
        ),
    ]
