# Generated by Django 6.0.4 on 2026-07-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_pacienteodontologo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='email_verificado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono_verificado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
