# Generated by Django 6.0.4 on 2026-07-03 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_paciente_email_verificado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado_validacion_datos',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado')], default='validado', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='origen_alta',
            field=models.CharField(choices=[('interno', 'Carga interna'), ('solicitud_publica', 'Solicitud publica')], default='interno', max_length=30),
        ),
        migrations.AddField(
            model_name='paciente',
            name='validado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_validados', to=settings.AUTH_USER_MODEL),
        ),
    ]
