# Generated by Django 6.0.4 on 2026-07-03 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_paciente_estado_validacion_datos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='archivado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='archivado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_archivados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paciente',
            name='motivo_archivado',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['activo', 'apellido', 'nombre'], name='pacientes_p_activo_5e916b_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['activo', 'documento'], name='pacientes_p_activo_eb4e93_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['archivado_en'], name='pacientes_p_archiva_ccea3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activo', True), ('archivado_en__isnull', True), ('archivado_por__isnull', True), ('motivo_archivado', '')), models.Q(('activo', False), ('archivado_en__isnull', False), models.Q(('motivo_archivado', ''), _negated=True)), _connector='OR'), name='paciente_archivo_consistente'),
        ),
    ]
