# Generated by Django 6.0.6 on 2026-07-17 00:00

import django.db.models.deletion
import django.utils.timezone
import indicaciones.models
import indicaciones.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historias', '0008_alter_accesoclinicoauditoria_accion'),
        ('pacientes', '0007_paciente_activo_paciente_archivado_en_and_more'),
        ('turnos', '0016_excepcionagenda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaIndicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('procedimiento', models.CharField(blank=True, max_length=150)),
                ('titulo_documento', models.CharField(max_length=180)),
                ('contenido', models.TextField()),
                ('pautas_alarma', models.TextField(blank=True)),
                ('recomendaciones_control', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantillas_indicaciones_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantillas_indicaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de indicación',
                'verbose_name_plural': 'Plantillas de indicaciones',
                'ordering': ['nombre', '-version'],
            },
        ),
        migrations.CreateModel(
            name='IndicacionPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('plantilla_version', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('titulo', models.CharField(max_length=180)),
                ('procedimiento', models.CharField(blank=True, max_length=180)),
                ('contenido', models.TextField()),
                ('pautas_alarma', models.TextField(blank=True)),
                ('recomendaciones_control', models.TextField(blank=True)),
                ('observaciones_personalizadas', models.TextField(blank=True)),
                ('proximo_control_en', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('snapshot_paciente', models.JSONField(default=dict, editable=False)),
                ('snapshot_profesional', models.JSONField(default=dict, editable=False)),
                ('snapshot_consultorio', models.JSONField(default=dict, editable=False)),
                ('snapshot_documento', models.JSONField(default=dict, editable=False)),
                ('emitida_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('anulada_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('pdf', models.FileField(blank=True, editable=False, max_length=255, storage=indicaciones.storage.almacenamiento_indicaciones_privado, upload_to=indicaciones.models.ruta_privada_indicacion)),
                ('pdf_sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('sello_integridad', models.CharField(blank=True, editable=False, max_length=64)),
                ('referencia_integridad', models.CharField(blank=True, editable=False, max_length=12)),
                ('email_destino', models.EmailField(blank=True, editable=False, max_length=254)),
                ('email_estado', models.CharField(choices=[('no_aplica', 'No aplica'), ('sin_destino', 'Sin email verificado'), ('pendiente', 'Email pendiente'), ('enviando', 'Enviando email'), ('enviado', 'Email enviado'), ('error', 'Error de email')], default='no_aplica', editable=False, max_length=20)),
                ('email_enviado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('email_ultimo_intento_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('email_intentos', models.PositiveIntegerField(default=0, editable=False)),
                ('email_clave_idempotencia', models.CharField(blank=True, editable=False, max_length=120)),
                ('ultimo_error_email', models.TextField(blank=True, editable=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicaciones_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('anulada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicaciones_anuladas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('emitida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicaciones_emitidas', to=settings.AUTH_USER_MODEL)),
                ('historia_clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicaciones_postoperatorias', to='historias.historiaclinica')),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicaciones_postoperatorias', to='turnos.odontologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicaciones_postoperatorias', to='pacientes.paciente')),
                ('reemplaza_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_reemplazo', to='indicaciones.indicacionpaciente')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicaciones_postoperatorias', to='turnos.turno')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicaciones_generadas', to='indicaciones.plantillaindicacion')),
            ],
            options={
                'verbose_name': 'Indicación postoperatoria',
                'verbose_name_plural': 'Indicaciones postoperatorias',
                'ordering': ['-emitida_en', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaIndicacionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('motivo', models.TextField()),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones_plantillas_indicaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones', to='indicaciones.plantillaindicacion')),
            ],
            options={
                'verbose_name': 'Versión de plantilla de indicación',
                'verbose_name_plural': 'Versiones de plantillas de indicaciones',
                'ordering': ['plantilla', 'numero_version'],
            },
        ),
        migrations.AddIndex(
            model_name='plantillaindicacion',
            index=models.Index(fields=['activa', 'nombre'], name='indicacione_activa_576579_idx'),
        ),
        migrations.AddConstraint(
            model_name='plantillaindicacion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='ind_plant_version_pos'),
        ),
        migrations.AddIndex(
            model_name='indicacionpaciente',
            index=models.Index(fields=['paciente', 'estado', '-emitida_en'], name='indicacione_pacient_5f7a20_idx'),
        ),
        migrations.AddIndex(
            model_name='indicacionpaciente',
            index=models.Index(fields=['odontologo', 'estado', '-emitida_en'], name='indicacione_odontol_fc22b8_idx'),
        ),
        migrations.AddIndex(
            model_name='indicacionpaciente',
            index=models.Index(fields=['email_estado', 'estado'], name='indicacione_email_e_96c164_idx'),
        ),
        migrations.AddIndex(
            model_name='indicacionpaciente',
            index=models.Index(fields=['plantilla', 'plantilla_version'], name='indicacione_plantil_304905_idx'),
        ),
        migrations.AddConstraint(
            model_name='indicacionpaciente',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('anulada_en__isnull', True), ('anulada_por__isnull', True), ('email_estado', 'no_aplica'), ('emitida_en__isnull', True), ('emitida_por__isnull', True), ('estado', 'borrador'), ('pdf', ''), ('pdf_sha256', ''), ('sello_integridad', '')), models.Q(('anulada_en__isnull', True), ('anulada_por__isnull', True), ('emitida_en__isnull', False), ('emitida_por__isnull', False), ('estado', 'emitida'), ('motivo_anulacion', ''), models.Q(('pdf', ''), _negated=True), models.Q(('pdf_sha256', ''), _negated=True), models.Q(('sello_integridad', ''), _negated=True)), models.Q(('anulada_en__isnull', False), ('anulada_por__isnull', False), ('emitida_en__isnull', False), ('emitida_por__isnull', False), ('estado', 'anulada'), models.Q(('motivo_anulacion', ''), _negated=True), models.Q(('pdf', ''), _negated=True), models.Q(('pdf_sha256', ''), _negated=True), models.Q(('sello_integridad', ''), _negated=True)), _connector='OR'), name='ind_documento_estado_coherente'),
        ),
        migrations.AddConstraint(
            model_name='indicacionpaciente',
            constraint=models.CheckConstraint(condition=models.Q(('reemplaza_a__isnull', True), models.Q(('pk', models.F('reemplaza_a')), _negated=True), _connector='OR'), name='ind_no_reemplazo_propio'),
        ),
        migrations.AddIndex(
            model_name='plantillaindicacionversion',
            index=models.Index(fields=['plantilla', 'numero_version'], name='indicacione_plantil_8a0924_idx'),
        ),
        migrations.AddConstraint(
            model_name='plantillaindicacionversion',
            constraint=models.UniqueConstraint(fields=('plantilla', 'numero_version'), name='ind_plant_version_unica'),
        ),
        migrations.AddConstraint(
            model_name='plantillaindicacionversion',
            constraint=models.CheckConstraint(condition=models.Q(('numero_version__gt', 0)), name='ind_plant_hist_num_pos'),
        ),
    ]
