# Generated by Django 6.0.4 on 2026-05-05 01:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('duracion_turno_minutos', models.PositiveSmallIntegerField(default=30)),
                ('hora_inicio_atencion', models.TimeField(default=datetime.time(9, 0))),
                ('hora_fin_atencion', models.TimeField(default=datetime.time(18, 0))),
                ('color_calendario', models.CharField(default='#2f80ed', max_length=7)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_odontologo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Odontologo',
                'verbose_name_plural': 'Odontologos',
                'ordering': ['usuario__last_name', 'usuario__first_name', 'usuario__username'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('duracion_minutos', models.PositiveSmallIntegerField(default=30)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('realizado', 'Realizado')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='turnos.odontologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha', 'hora_inicio'],
                'indexes': [models.Index(fields=['fecha', 'hora_inicio'], name='turnos_turn_fecha_9c2808_idx'), models.Index(fields=['odontologo', 'fecha'], name='turnos_turn_odontol_607782_idx'), models.Index(fields=['estado'], name='turnos_turn_estado_3fab1e_idx')],
            },
        ),
    ]
