# Generated by Django 6.0.4 on 2026-05-05 02:23

import django.db.models.deletion
from django.db import migrations, models


def crear_disponibilidades_iniciales(apps, schema_editor):
    odontologo_model = apps.get_model('turnos', 'Odontologo')
    disponibilidad_model = apps.get_model('turnos', 'DisponibilidadOdontologo')

    disponibilidades = []

    for odontologo in odontologo_model.objects.all():
        for dia_semana in range(5):
            disponibilidades.append(
                disponibilidad_model(
                    odontologo=odontologo,
                    dia_semana=dia_semana,
                    hora_inicio=odontologo.hora_inicio_atencion,
                    hora_fin=odontologo.hora_fin_atencion,
                    activo=True,
                )
            )

    disponibilidad_model.objects.bulk_create(disponibilidades)


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadOdontologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='turnos.odontologo')),
            ],
            options={
                'verbose_name': 'Disponibilidad de odontologo',
                'verbose_name_plural': 'Disponibilidades de odontologos',
                'ordering': ['odontologo', 'dia_semana', 'hora_inicio'],
                'indexes': [models.Index(fields=['odontologo', 'dia_semana', 'activo'], name='turnos_disp_odontol_b78276_idx')],
            },
        ),
        migrations.RunPython(crear_disponibilidades_iniciales, migrations.RunPython.noop),
    ]
