# Generated by Django 6.0.4 on 2026-05-06 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_disponibilidadodontologo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarConexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('token_expira_en', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('ultimo_error', models.TextField(blank=True)),
                ('sincronizado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('odontologo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_conexion', to='turnos.odontologo')),
            ],
            options={
                'verbose_name': 'Conexion con Google Calendar',
                'verbose_name_plural': 'Conexiones con Google Calendar',
                'ordering': ['odontologo'],
                'indexes': [models.Index(fields=['activa'], name='turnos_goog_activa_f852fc_idx')],
            },
        ),
    ]
