# Generated by Django 6.0.4 on 2026-05-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_googlecalendarconexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='recordatorio_email_enviado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='recordatorio_email_ultimo_error',
            field=models.TextField(blank=True),
        ),
    ]
