# Generated by Django 6.0.4 on 2026-05-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_odontologo_foto_perfil_y_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontologo',
            name='celular',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
