# Generated by Django 6.0.4 on 2026-05-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0007_odontologo_celular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilidadodontologo',
            options={'ordering': ['odontologo', 'dia_semana', 'hora_inicio'], 'verbose_name': 'Disponibilidad de odontólogo', 'verbose_name_plural': 'Disponibilidades de odontólogos'},
        ),
        migrations.AlterModelOptions(
            name='googlecalendarconexion',
            options={'ordering': ['odontologo'], 'verbose_name': 'Conexión con Google Calendar', 'verbose_name_plural': 'Conexiones con Google Calendar'},
        ),
        migrations.AlterModelOptions(
            name='odontologo',
            options={'ordering': ['usuario__last_name', 'usuario__first_name', 'usuario__username'], 'verbose_name': 'Odontólogo', 'verbose_name_plural': 'Odontólogos'},
        ),
        migrations.AlterField(
            model_name='disponibilidadodontologo',
            name='dia_semana',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
    ]
