# Generated by Django 6.0.4 on 2026-05-13 14:48

from django.db import migrations, models


def convertir_turnos_realizados_a_confirmados(apps, schema_editor):
    Turno = apps.get_model("turnos", "Turno")
    Turno.objects.filter(estado="realizado").update(estado="confirmado")


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0008_alter_disponibilidadodontologo_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            convertir_turnos_realizados_a_confirmados,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
