# Generated by Django 6.0.4 on 2026-05-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0009_alter_turno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='motivo_cancelacion_paciente',
            field=models.TextField(blank=True),
        ),
    ]
