# Generated by Django 6.0.4 on 2026-07-02 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0010_turno_motivo_cancelacion_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoAgendaOdontologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos_agenda', to='turnos.odontologo')),
            ],
            options={
                'verbose_name': 'Bloqueo de agenda',
                'verbose_name_plural': 'Bloqueos de agenda',
                'ordering': ['odontologo', 'fecha'],
                'indexes': [models.Index(fields=['odontologo', 'fecha'], name='turnos_bloq_odontol_468c56_idx')],
                'constraints': [models.UniqueConstraint(fields=('odontologo', 'fecha'), name='uniq_bloqueo_agenda_odontologo_fecha')],
            },
        ),
    ]
