# Generated by Django 6.0.4 on 2026-07-02 09:50

import turnos.fields
from django.db import migrations


def cifrar_tokens_oauth_existentes(apps, schema_editor):
    GoogleCalendarConexion = apps.get_model("turnos", "GoogleCalendarConexion")

    for conexion in GoogleCalendarConexion.objects.all().iterator():
        if not conexion.access_token and not conexion.refresh_token:
            continue

        conexion.save(update_fields=["access_token", "refresh_token", "actualizado_en"])


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0011_bloqueoagendaodontologo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecalendarconexion',
            name='access_token',
            field=turnos.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='googlecalendarconexion',
            name='refresh_token',
            field=turnos.fields.EncryptedTextField(blank=True),
        ),
        migrations.RunPython(cifrar_tokens_oauth_existentes, migrations.RunPython.noop),
    ]
