# Generated by Django 6.0.4 on 2026-07-03 02:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_paciente_email_verificado_en_and_more'),
        ('turnos', '0012_alter_googlecalendarconexion_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='version_publica',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name='AccionPublicaTurno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_accion', models.CharField(choices=[('cancelar', 'Cancelar'), ('reprogramar', 'Reprogramar')], max_length=20)),
                ('token_hash', models.TextField()),
                ('version_turno', models.UUIDField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('utilizado_en', models.DateTimeField(blank=True, null=True)),
                ('revocado_en', models.DateTimeField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_publicas_turnos', to='pacientes.paciente')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_publicas', to='turnos.turno')),
            ],
            options={
                'verbose_name': 'Acción pública de turno',
                'verbose_name_plural': 'Acciones públicas de turnos',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['turno', 'tipo_accion', 'revocado_en', 'utilizado_en'], name='turnos_acci_turno_i_c83bc9_idx'), models.Index(fields=['paciente', 'expira_en'], name='turnos_acci_pacient_5d7392_idx'), models.Index(fields=['expira_en'], name='turnos_acci_expira__8c3991_idx')],
            },
        ),
        migrations.CreateModel(
            name='DesafioAccesoPublicoTurnos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('ficticio', 'Ficticio')], default='email', max_length=20)),
                ('codigo_hash', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('validado_en', models.DateTimeField(blank=True, null=True)),
                ('invalidado_en', models.DateTimeField(blank=True, null=True)),
                ('intentos_fallidos', models.PositiveSmallIntegerField(default=0)),
                ('cantidad_envios', models.PositiveSmallIntegerField(default=0)),
                ('ultimo_envio_en', models.DateTimeField(blank=True, null=True)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('dni_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desafios_acceso_turnos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Desafío de acceso público a turnos',
                'verbose_name_plural': 'Desafíos de acceso público a turnos',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['expira_en'], name='turnos_desa_expira__bdfc48_idx'), models.Index(fields=['paciente', 'invalidado_en', 'validado_en'], name='turnos_desa_pacient_c99fee_idx'), models.Index(fields=['dni_hash', 'creado_en'], name='turnos_desa_dni_has_6e104b_idx')],
            },
        ),
    ]
