# Generated by Django 6.0.4 on 2026-07-03 04:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_paciente_estado_validacion_datos_and_more'),
        ('turnos', '0013_turno_version_publica_accionpublicaturno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudTurnoPublica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documento_enviado', models.CharField(max_length=20)),
                ('nombre_enviado', models.CharField(max_length=100)),
                ('apellido_enviado', models.CharField(max_length=100)),
                ('telefono_enviado', models.CharField(max_length=30)),
                ('email_enviado', models.EmailField(blank=True, max_length=254)),
                ('motivo_enviado', models.CharField(blank=True, max_length=200)),
                ('paciente_existente', models.BooleanField(default=False)),
                ('requiere_revision', models.BooleanField(default=False)),
                ('diferencias_detectadas', models.JSONField(blank=True, default=dict)),
                ('estado_revision', models.CharField(choices=[('sin_diferencias', 'Sin diferencias'), ('pendiente', 'Pendiente de revision'), ('revisada_sin_cambios', 'Revisada sin cambios'), ('cambios_aplicados', 'Cambios aplicados'), ('rechazada', 'Descartada')], default='pendiente', max_length=30)),
                ('revisada_en', models.DateTimeField(blank=True, null=True)),
                ('observaciones_revision', models.TextField(blank=True)),
                ('campos_actualizados', models.JSONField(blank=True, default=list)),
                ('campos_descartados', models.JSONField(blank=True, default=list)),
                ('notificacion_contacto_existente_en', models.DateTimeField(blank=True, null=True)),
                ('notificacion_contacto_existente_error', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_turno_publicas', to='pacientes.paciente')),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_publicas_revisadas', to=settings.AUTH_USER_MODEL)),
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_publica', to='turnos.turno')),
            ],
            options={
                'verbose_name': 'Solicitud publica de turno',
                'verbose_name_plural': 'Solicitudes publicas de turnos',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['estado_revision', 'creado_en'], name='turnos_soli_estado__cd3781_idx'), models.Index(fields=['requiere_revision', 'creado_en'], name='turnos_soli_requier_1d3097_idx'), models.Index(fields=['paciente', 'creado_en'], name='turnos_soli_pacient_ecd614_idx'), models.Index(fields=['turno'], name='turnos_soli_turno_i_3c20e8_idx')],
            },
        ),
    ]
