# Generated by Django 6.0.4 on 2026-07-03 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0014_solicitudturnopublica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudturnopublica',
            name='turno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_publica', to='turnos.turno'),
        ),
    ]
