# Generated by Django 6.0.7 on 2026-07-17 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def completar_snapshots_legacy(apps, schema_editor):
    Turno = apps.get_model("turnos", "Turno")
    Turno.objects.filter(duracion_atencion_minutos__isnull=True).update(
        duracion_atencion_minutos=models.F("duracion_minutos"),
        margen_posterior_minutos_snapshot=0,
        clasificacion_horario="legacy",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0016_excepcionagenda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudturnopublica',
            name='algoritmo_version',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='solicitudturnopublica',
            name='duracion_atencion_snapshot',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudturnopublica',
            name='duracion_bloqueada_snapshot',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudturnopublica',
            name='horario_clasificacion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudturnopublica',
            name='horario_puntaje',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudturnopublica',
            name='margen_posterior_snapshot',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solicitudturnopublica',
            name='tipo_turno_nombre_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='turno',
            name='algoritmo_horario_version',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='turno',
            name='clasificacion_horario',
            field=models.CharField(blank=True, choices=[('recomendado', 'Recomendado'), ('alternativo', 'Alternativo'), ('interno', 'Creación interna'), ('legacy', 'Turno anterior')], max_length=20),
        ),
        migrations.AddField(
            model_name='turno',
            name='duracion_atencion_minutos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='margen_posterior_minutos_snapshot',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turno',
            name='puntaje_horario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='tipo_turno_nombre_snapshot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(
            completar_snapshots_legacy,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='ConfiguracionAgendaInteligente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('intervalo_inicio_minutos', models.PositiveSmallIntegerField(default=15)),
                ('hueco_minimo_util_minutos', models.PositiveSmallIntegerField(default=30)),
                ('cantidad_horarios_recomendados', models.PositiveSmallIntegerField(default=4)),
                ('cantidad_horarios_alternativos', models.PositiveSmallIntegerField(default=8)),
                ('preservar_bloques_largos', models.BooleanField(default=True)),
                ('bloque_largo_minutos', models.PositiveSmallIntegerField(default=90)),
                ('modo_compactacion', models.CharField(choices=[('equilibrado', 'Equilibrado'), ('inicio', 'Priorizar comienzo de bloque'), ('final', 'Priorizar final de bloque')], default='equilibrado', max_length=20)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('odontologo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_agenda_inteligente', to='turnos.odontologo')),
            ],
            options={
                'verbose_name': 'Configuración de agenda inteligente',
                'verbose_name_plural': 'Configuraciones de agenda inteligente',
            },
        ),
        migrations.CreateModel(
            name='TipoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('descripcion_publica', models.CharField(blank=True, max_length=240)),
                ('icono', models.CharField(blank=True, choices=[('calendar', 'Calendario'), ('check', 'Control'), ('info', 'Consulta'), ('clinical', 'Clínico'), ('appointments', 'Turno'), ('clock', 'Reloj')], max_length=50)),
                ('orden_publico', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('visible_publicamente', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_turno_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_turno_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de turno',
                'verbose_name_plural': 'Tipos de turno',
                'ordering': ['orden_publico', 'nombre', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='solicitudturnopublica',
            name='tipo_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_publicas', to='turnos.tipoturno'),
        ),
        migrations.AddField(
            model_name='turno',
            name='tipo_turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='turnos.tipoturno'),
        ),
        migrations.CreateModel(
            name='TipoTurnoOdontologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_atencion_minutos', models.PositiveSmallIntegerField()),
                ('margen_posterior_minutos', models.PositiveSmallIntegerField(default=0)),
                ('reserva_publica', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_tipos_turno', to='turnos.odontologo')),
                ('tipo_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_odontologos', to='turnos.tipoturno')),
            ],
            options={
                'verbose_name': 'Configuración de tipo por odontólogo',
                'verbose_name_plural': 'Configuraciones de tipos por odontólogo',
                'ordering': ['odontologo', 'tipo_turno__orden_publico', 'tipo_turno__nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='tipoturno',
            index=models.Index(fields=['activo', 'visible_publicamente', 'orden_publico'], name='turnos_tipo_activo_c5c3e6_idx'),
        ),
        migrations.AddIndex(
            model_name='tipoturnoodontologo',
            index=models.Index(fields=['odontologo', 'activo', 'reserva_publica'], name='turnos_tipo_odontol_0e24ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='tipoturnoodontologo',
            constraint=models.UniqueConstraint(fields=('odontologo', 'tipo_turno'), name='uniq_tipo_turno_por_odontologo'),
        ),
    ]
