# Generated by Django 6.0.7 on 2026-07-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0017_agenda_inteligente'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotenciaSolicitudPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('estado', models.CharField(choices=[('processing', 'Procesando'), ('completed', 'Completada')], default='processing', max_length=20)),
                ('procesamiento_expira_en', models.DateTimeField(blank=True, null=True)),
                ('expira_en', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Idempotencia de solicitud pública',
                'verbose_name_plural': 'Idempotencias de solicitudes públicas',
                'indexes': [models.Index(fields=['expira_en'], name='turnos_idemp_expira_idx'), models.Index(fields=['estado', 'procesamiento_expira_en'], name='turnos_idemp_lease_idx')],
            },
        ),
        migrations.CreateModel(
            name='LimitePublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(max_length=64)),
                ('sujeto_hash', models.CharField(max_length=64)),
                ('ventana_inicio', models.DateTimeField()),
                ('contador', models.PositiveIntegerField(default=1)),
                ('expira_en', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Límite público',
                'verbose_name_plural': 'Límites públicos',
                'indexes': [models.Index(fields=['expira_en'], name='turnos_limite_expira_idx'), models.Index(fields=['ambito', 'sujeto_hash', 'ventana_inicio'], name='turnos_limite_busqueda_idx')],
                'constraints': [models.UniqueConstraint(fields=('ambito', 'sujeto_hash', 'ventana_inicio'), name='turnos_limite_ventana_unica'), models.CheckConstraint(condition=models.Q(('contador__gte', 0)), name='turnos_limite_contador_gte_0')],
            },
        ),
    ]
