"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from .database import configurar_base_de_datos
from .env import cargar_env, env, env_bool, env_list

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
cargar_env(BASE_DIR.parent / ".env")
cargar_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret.
SECRET_KEY = env("DJANGO_SECRET_KEY", "django-insecure-local-development-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)

if not DEBUG and SECRET_KEY == "django-insecure-local-development-key":
    raise RuntimeError("DJANGO_SECRET_KEY debe configurarse cuando DJANGO_DEBUG=False.")

DEFAULT_ALLOWED_HOSTS = ["127.0.0.1", "localhost", "testserver"] if DEBUG else []
ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", DEFAULT_ALLOWED_HOSTS)

if not DEBUG and not ALLOWED_HOSTS:
    raise RuntimeError("DJANGO_ALLOWED_HOSTS debe configurarse cuando DJANGO_DEBUG=False.")

CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS")
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", False)
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", not DEBUG)
SECURE_HSTS_SECONDS = int(env("DJANGO_SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", False)

if env_bool("DJANGO_SECURE_PROXY_SSL_HEADER", False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pacientes',
    'turnos',
    'historias',
    'odontogramas',
    'usuarios.apps.UsuariosConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'usuarios.context_processors.permisos_usuario',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": configurar_base_de_datos(env("DATABASE_URL"), BASE_DIR)
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"
MEDIA_STORAGE_BACKEND = env(
    "MEDIA_STORAGE_BACKEND",
    "django.core.files.storage.FileSystemStorage",
)
SUPABASE_STORAGE_URL = env("SUPABASE_STORAGE_URL")
SUPABASE_STORAGE_BUCKET = env("SUPABASE_STORAGE_BUCKET", "historias-clinicas")
SUPABASE_STORAGE_SERVICE_ROLE_KEY = env("SUPABASE_STORAGE_SERVICE_ROLE_KEY")
SUPABASE_STORAGE_TIMEOUT = int(env("SUPABASE_STORAGE_TIMEOUT", "30"))
SUPABASE_STORAGE_CACHE_CONTROL = env("SUPABASE_STORAGE_CACHE_CONTROL", "3600")
SUPABASE_STORAGE_SIGNED_URL_SECONDS = int(
    env("SUPABASE_STORAGE_SIGNED_URL_SECONDS", "300")
)
STORAGES = {
    "default": {
        "BACKEND": MEDIA_STORAGE_BACKEND,
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

REDIS_URL = env("REDIS_URL")
TURNOS_PUBLIC_REDIS_REQUIRED = env_bool("TURNOS_PUBLIC_REDIS_REQUIRED", not DEBUG)

if TURNOS_PUBLIC_REDIS_REQUIRED and not REDIS_URL:
    raise RuntimeError("REDIS_URL debe configurarse cuando TURNOS_PUBLIC_REDIS_REQUIRED=True.")

CACHES = {
    "default": (
        {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "KEY_PREFIX": "gestor_turnos",
        }
        if REDIS_URL
        else {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "gestor-turnos-local",
            "KEY_PREFIX": "gestor_turnos",
        }
    )
}

ODONTOGRAMA_FEATURE_ENABLED = env_bool("ODONTOGRAMA_FEATURE_ENABLED", False)
TURNOS_PUBLIC_ACCESS_REQUEST_LIMIT = int(env("TURNOS_PUBLIC_ACCESS_REQUEST_LIMIT", "5"))
TURNOS_PUBLIC_ACCESS_REQUEST_WINDOW_SECONDS = int(
    env("TURNOS_PUBLIC_ACCESS_REQUEST_WINDOW_SECONDS", "900")
)
TURNOS_PUBLIC_OTP_ATTEMPTS = int(env("TURNOS_PUBLIC_OTP_ATTEMPTS", "5"))
TURNOS_PUBLIC_OTP_SECONDS = int(env("TURNOS_PUBLIC_OTP_SECONDS", "600"))
TURNOS_PUBLIC_SESSION_SECONDS = int(env("TURNOS_PUBLIC_SESSION_SECONDS", "900"))
TURNOS_PUBLIC_RESEND_SECONDS = int(env("TURNOS_PUBLIC_RESEND_SECONDS", "60"))
TURNOS_PUBLIC_RESEND_LIMIT = int(env("TURNOS_PUBLIC_RESEND_LIMIT", "3"))
TURNOS_PUBLIC_RESEND_WINDOW_SECONDS = int(env("TURNOS_PUBLIC_RESEND_WINDOW_SECONDS", "3600"))
TURNOS_PUBLIC_ACTION_TOKEN_SECONDS = int(env("TURNOS_PUBLIC_ACTION_TOKEN_SECONDS", "900"))
TURNOS_PUBLIC_ACTION_LIMIT = int(env("TURNOS_PUBLIC_ACTION_LIMIT", "20"))
TURNOS_PUBLIC_ACTION_WINDOW_SECONDS = int(env("TURNOS_PUBLIC_ACTION_WINDOW_SECONDS", "900"))
TURNSTILE_ENABLED = env_bool("TURNSTILE_ENABLED", False)
TURNSTILE_SITE_KEY = env("TURNSTILE_SITE_KEY")
TURNSTILE_SECRET_KEY = env("TURNSTILE_SECRET_KEY")
TURNSTILE_VERIFY_URL = env(
    "TURNSTILE_VERIFY_URL",
    "https://challenges.cloudflare.com/turnstile/v0/siteverify",
)
TURNSTILE_REQUIRED_AFTER_ATTEMPTS = int(env("TURNSTILE_REQUIRED_AFTER_ATTEMPTS", "3"))
TURNSTILE_TIMEOUT_SECONDS = int(env("TURNSTILE_TIMEOUT_SECONDS", "5"))

if TURNSTILE_ENABLED and (not TURNSTILE_SITE_KEY or not TURNSTILE_SECRET_KEY):
    raise RuntimeError("TURNSTILE_SITE_KEY y TURNSTILE_SECRET_KEY deben configurarse si TURNSTILE_ENABLED=True.")

OAUTH_TOKEN_ENCRYPTION_KEY = env("OAUTH_TOKEN_ENCRYPTION_KEY")
OAUTH_TOKEN_ENCRYPTION_KEY_REQUIRED = not DEBUG

if OAUTH_TOKEN_ENCRYPTION_KEY_REQUIRED and not OAUTH_TOKEN_ENCRYPTION_KEY:
    raise RuntimeError("OAUTH_TOKEN_ENCRYPTION_KEY debe configurarse cuando DJANGO_DEBUG=False.")

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'inicio'
LOGOUT_REDIRECT_URL = 'login'

DJANGO_LOG_LEVEL = env("DJANGO_LOG_LEVEL", "INFO").upper()
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "[{levelname}] {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "pacientes": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "turnos": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "historias": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "odontogramas": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "usuarios": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
    },
}

EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = env("EMAIL_HOST", "localhost")
EMAIL_PORT = int(env("EMAIL_PORT", "25"))
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", False)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", False)
EMAIL_TIMEOUT = int(env("EMAIL_TIMEOUT", "10"))
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", "turnos@localhost")
EMAIL_API_PROVIDER = env("EMAIL_API_PROVIDER", "resend")
EMAIL_API_KEY = env("EMAIL_API_KEY")
EMAIL_API_URL = env("EMAIL_API_URL")
TURNOS_RECORDATORIO_HORAS = int(env("TURNOS_RECORDATORIO_HORAS", "24"))

if EMAIL_USE_TLS and EMAIL_USE_SSL:
    raise RuntimeError("EMAIL_USE_TLS y EMAIL_USE_SSL no pueden estar activos al mismo tiempo.")

GOOGLE_CALENDAR_CLIENT_ID = env("GOOGLE_CALENDAR_CLIENT_ID")
GOOGLE_CALENDAR_CLIENT_SECRET = env("GOOGLE_CALENDAR_CLIENT_SECRET")
GOOGLE_CALENDAR_CLIENT_SECRETS_FILE = env("GOOGLE_CALENDAR_CLIENT_SECRETS_FILE")
GOOGLE_CALENDAR_REDIRECT_URI = env(
    "GOOGLE_CALENDAR_REDIRECT_URI",
    "http://127.0.0.1:8000/turnos/google-calendar/callback/",
)
GOOGLE_CALENDAR_SCOPES = env_list(
    "GOOGLE_CALENDAR_SCOPES",
    ["https://www.googleapis.com/auth/calendar.events"],
)
