from django.urls import path

from .public_access.views import (
    CancelarTurnoPublicoSeguroView,
    CerrarAccesoPublicoTurnosView,
    HorariosReprogramacionPublicaJsonView,
    MisTurnosPublicoView,
    ReprogramarTurnoPublicoSeguroView,
    SolicitarAccesoPublicoTurnosView,
    VerificarAccesoPublicoTurnosView,
)
from .views import (
    AgendaDiaView,
    AgendaSemanaView,
    AlertasAdministrativasPublicasView,
    ConfiguracionAgendaUpdateView,
    ConfiguracionServiciosView,
    ExcepcionAgendaCreateView,
    ExcepcionAgendaDeactivateView,
    ExcepcionAgendaListView,
    ExcepcionAgendaUpdateView,
    GoogleCalendarCallbackView,
    GoogleCalendarConectarView,
    GoogleCalendarConexionView,
    GoogleCalendarDesconectarView,
    HorariosDisponiblesJsonView,
    SolicitudTurnoPublicaDatosView,
    SolicitudTurnoPublicaHorariosView,
    SolicitudTurnoPublicaListView,
    SolicitudTurnoPublicaOkView,
    SolicitudTurnoPublicaRevisionView,
    SolicitudTurnoPublicaTiposView,
    SolicitudTurnoPublicaView,
    TipoTurnoCreateView,
    TipoTurnoOdontologoCreateView,
    TipoTurnoOdontologoUpdateView,
    TipoTurnoUpdateView,
    TurnoCancelView,
    TurnoConfirmView,
    TurnoCreateView,
    TurnoDetailView,
    TurnoListView,
    TurnoReintentarSincronizacionGoogleCalendarView,
    TurnoReprogramView,
    TurnoSolicitudPublicaRechazarView,
    TurnoUpdateView,
)

app_name = "turnos"

urlpatterns = [
    path("", TurnoListView.as_view(), name="lista"),
    path("nuevo/", TurnoCreateView.as_view(), name="crear"),
    path(
        "horarios-disponibles/",
        HorariosDisponiblesJsonView.as_view(),
        name="horarios_disponibles",
    ),
    path("solicitar/", SolicitudTurnoPublicaView.as_view(), name="solicitud_publica"),
    path(
        "solicitar/tipos/",
        SolicitudTurnoPublicaTiposView.as_view(),
        name="solicitud_publica_tipos",
    ),
    path(
        "solicitar/horarios/",
        SolicitudTurnoPublicaHorariosView.as_view(),
        name="solicitud_publica_horarios",
    ),
    path(
        "solicitar/datos/",
        SolicitudTurnoPublicaDatosView.as_view(),
        name="solicitud_publica_datos",
    ),
    path(
        "solicitar/gracias/",
        SolicitudTurnoPublicaOkView.as_view(),
        name="solicitud_publica_ok",
    ),
    path(
        "solicitudes-publicas/",
        SolicitudTurnoPublicaListView.as_view(),
        name="solicitudes_publicas",
    ),
    path(
        "alertas-administrativas/",
        AlertasAdministrativasPublicasView.as_view(),
        name="alertas_administrativas",
    ),
    path(
        "solicitudes-publicas/<uuid:pk>/",
        SolicitudTurnoPublicaRevisionView.as_view(),
        name="solicitud_publica_revision",
    ),
    path(
        "mis-turnos/solicitar-acceso/",
        SolicitarAccesoPublicoTurnosView.as_view(),
        name="acceso_publico_solicitar",
    ),
    path(
        "mis-turnos/verificar/",
        VerificarAccesoPublicoTurnosView.as_view(),
        name="acceso_publico_verificar",
    ),
    path("mis-turnos/", MisTurnosPublicoView.as_view(), name="mis_turnos_publico"),
    path(
        "mis-turnos/cerrar/",
        CerrarAccesoPublicoTurnosView.as_view(),
        name="acceso_publico_cerrar",
    ),
    path(
        "mis-turnos/<uuid:accion_id>/cancelar/",
        CancelarTurnoPublicoSeguroView.as_view(),
        name="mis_turnos_cancelar",
    ),
    path(
        "mis-turnos/<uuid:accion_id>/reprogramar/",
        ReprogramarTurnoPublicoSeguroView.as_view(),
        name="mis_turnos_reprogramar",
    ),
    path(
        "mis-turnos/<uuid:accion_id>/reprogramar/horarios/",
        HorariosReprogramacionPublicaJsonView.as_view(),
        name="mis_turnos_reprogramar_horarios",
    ),
    path("agenda/dia/", AgendaDiaView.as_view(), name="agenda_dia"),
    path("agenda/semana/", AgendaSemanaView.as_view(), name="agenda_semana"),
    path(
        "configuracion/servicios/",
        ConfiguracionServiciosView.as_view(),
        name="configuracion_servicios",
    ),
    path(
        "configuracion/servicios/profesional/<int:pk>/nuevo/",
        TipoTurnoOdontologoCreateView.as_view(),
        name="servicio_odontologo_crear",
    ),
    path(
        "configuracion/servicios/<int:pk>/editar/",
        TipoTurnoOdontologoUpdateView.as_view(),
        name="servicio_odontologo_editar",
    ),
    path(
        "configuracion/agenda/<int:pk>/editar/",
        ConfiguracionAgendaUpdateView.as_view(),
        name="configuracion_agenda_editar",
    ),
    path(
        "configuracion/tipos/nuevo/",
        TipoTurnoCreateView.as_view(),
        name="tipo_turno_crear",
    ),
    path(
        "configuracion/tipos/<int:pk>/editar/",
        TipoTurnoUpdateView.as_view(),
        name="tipo_turno_editar",
    ),
    path("excepciones/", ExcepcionAgendaListView.as_view(), name="excepciones"),
    path("excepciones/nueva/", ExcepcionAgendaCreateView.as_view(), name="excepcion_crear"),
    path(
        "excepciones/<int:pk>/editar/",
        ExcepcionAgendaUpdateView.as_view(),
        name="excepcion_editar",
    ),
    path(
        "excepciones/<int:pk>/desactivar/",
        ExcepcionAgendaDeactivateView.as_view(),
        name="excepcion_desactivar",
    ),
    path(
        "google-calendar/",
        GoogleCalendarConexionView.as_view(),
        name="google_calendar",
    ),
    path(
        "google-calendar/conectar/",
        GoogleCalendarConectarView.as_view(),
        name="google_calendar_conectar",
    ),
    path(
        "google-calendar/callback/",
        GoogleCalendarCallbackView.as_view(),
        name="google_calendar_callback",
    ),
    path(
        "google-calendar/desconectar/",
        GoogleCalendarDesconectarView.as_view(),
        name="google_calendar_desconectar",
    ),
    path("<int:pk>/", TurnoDetailView.as_view(), name="detalle"),
    path("<int:pk>/reprogramar/", TurnoReprogramView.as_view(), name="reprogramar"),
    path("<int:pk>/editar/", TurnoUpdateView.as_view(), name="editar"),
    path("<int:pk>/confirmar/", TurnoConfirmView.as_view(), name="confirmar"),
    path(
        "<int:pk>/rechazar-solicitud/",
        TurnoSolicitudPublicaRechazarView.as_view(),
        name="rechazar_solicitud_publica",
    ),
    path("<int:pk>/cancelar/", TurnoCancelView.as_view(), name="cancelar"),
    path(
        "<int:pk>/google-calendar/reintentar/",
        TurnoReintentarSincronizacionGoogleCalendarView.as_view(),
        name="reintentar_google_calendar",
    ),
]
