# Generated by Django 6.0.4 on 2026-05-09 02:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('turnos', '0004_turno_recordatorio_email_enviado_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('motivo_consulta', models.TextField()),
                ('diagnostico', models.TextField(blank=True)),
                ('tratamiento_realizado', models.TextField(blank=True)),
                ('pieza_dental', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('proximo_control', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historias_clinicas', to='turnos.odontologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historias_clinicas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Historia clinica',
                'verbose_name_plural': 'Historias clinicas',
                'ordering': ['-fecha', '-creado_en'],
                'indexes': [models.Index(fields=['paciente', '-fecha'], name='historias_h_pacient_e81da0_idx'), models.Index(fields=['odontologo', '-fecha'], name='historias_h_odontol_aaa048_idx')],
            },
        ),
    ]
