# Generated by Django 6.0.4 on 2026-05-10 04:16

import django.db.models.deletion
import historias.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historias_clinicas_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historias_clinicas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoriaClinicaAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=historias.models.ruta_adjunto_historia)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('tamano_bytes', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='historias.historiaclinica')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_historia_clinica', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjunto de historia clinica',
                'verbose_name_plural': 'Adjuntos de historia clinica',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['historia', '-creado_en'], name='historias_h_histori_32475a_idx')],
            },
        ),
    ]
