# Generated by Django 6.0.4 on 2026-05-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0002_historiaclinica_actualizado_por_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiaclinica',
            options={'ordering': ['-fecha', '-creado_en'], 'verbose_name': 'Historia clínica', 'verbose_name_plural': 'Historias clínicas'},
        ),
        migrations.AlterModelOptions(
            name='historiaclinicaadjunto',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Adjunto de historia clínica', 'verbose_name_plural': 'Adjuntos de historia clínica'},
        ),
    ]
