# Generated by Django 6.0.4 on 2026-07-03 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0003_alter_historiaclinica_options_and_more'),
        ('pacientes', '0007_paciente_activo_paciente_archivado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoClinicoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_solicitado', models.CharField(blank=True, max_length=120)),
                ('accion', models.CharField(choices=[('ver_paciente', 'Ver paciente'), ('ver_historia', 'Ver historia clinica'), ('ver_detalle_historia', 'Ver detalle de historia'), ('crear_historia', 'Crear historia clinica'), ('editar_historia', 'Editar historia clinica'), ('abrir_adjunto', 'Abrir adjunto clinico'), ('ver_ficha', 'Ver ficha odontologica'), ('editar_ficha', 'Editar ficha odontologica'), ('ver_odontograma', 'Ver odontograma'), ('editar_odontograma', 'Editar odontograma'), ('iniciar_emergencia', 'Iniciar acceso de emergencia'), ('finalizar_emergencia', 'Finalizar acceso de emergencia'), ('archivar_paciente', 'Archivar paciente'), ('reactivar_paciente', 'Reactivar paciente'), ('solicitud_publica_paciente_archivado', 'Solicitud publica de paciente archivado'), ('otp_paciente_archivado', 'OTP solicitado para paciente archivado')], max_length=50)),
                ('resultado', models.CharField(choices=[('permitido', 'Permitido'), ('denegado', 'Denegado'), ('error', 'Error')], max_length=20)),
                ('politica', models.CharField(blank=True, choices=[('asociacion_activa', 'Asociacion activa'), ('compartido', 'Datos compartidos'), ('emergencia', 'Emergencia'), ('administrativa', 'Administrativa'), ('sistema', 'Sistema'), ('sin_permiso', 'Sin permiso'), ('paciente_archivado', 'Paciente archivado')], max_length=40)),
                ('motivo', models.TextField(blank=True)),
                ('ruta', models.CharField(blank=True, max_length=255)),
                ('metodo', models.CharField(blank=True, max_length=12)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('es_emergencia', models.BooleanField(default=False)),
                ('es_acceso_compartido', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('adjunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_acceso', to='historias.historiaclinicaadjunto')),
                ('historia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_acceso', to='historias.historiaclinica')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_acceso_clinico', to='pacientes.paciente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_acceso_clinico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria de acceso clinico',
                'verbose_name_plural': 'Auditorias de acceso clinico',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['paciente', '-creado_en'], name='historias_a_pacient_3148fc_idx'), models.Index(fields=['usuario', '-creado_en'], name='historias_a_usuario_c7fbe4_idx'), models.Index(fields=['accion', '-creado_en'], name='historias_a_accion_00a5bb_idx'), models.Index(fields=['resultado', '-creado_en'], name='historias_a_resulta_e59b97_idx'), models.Index(fields=['es_emergencia', '-creado_en'], name='historias_a_es_emer_eee9ce_idx')],
            },
        ),
    ]
