# Generated by Django 6.0.6 on 2026-07-16 18:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0004_accesoclinicoauditoria'),
        ('pacientes', '0007_paciente_activo_paciente_archivado_en_and_more'),
        ('turnos', '0016_excepcionagenda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinicaEnmienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_enmienda', models.PositiveIntegerField()),
                ('texto', models.TextField()),
                ('motivo', models.TextField()),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('hash_anterior', models.CharField(blank=True, editable=False, max_length=64)),
                ('hash_integridad', models.CharField(editable=False, max_length=64)),
            ],
            options={
                'verbose_name': 'Enmienda de historia clínica',
                'verbose_name_plural': 'Enmiendas de historia clínica',
                'ordering': ['numero_enmienda', 'creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinicaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('motivo', models.TextField()),
                ('hash_anterior', models.CharField(blank=True, editable=False, max_length=64)),
                ('hash_integridad', models.CharField(editable=False, max_length=64)),
            ],
            options={
                'verbose_name': 'Versión de historia clínica',
                'verbose_name_plural': 'Versiones de historia clínica',
                'ordering': ['numero_version', 'creado_en'],
            },
        ),
        migrations.AlterModelOptions(
            name='accesoclinicoauditoria',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Auditoría de acceso clínico', 'verbose_name_plural': 'Auditorías de acceso clínico'},
        ),
        migrations.AlterModelOptions(
            name='historiaclinica',
            options={'ordering': ['-numero_asiento', '-fecha_hora_atencion', '-creado_en'], 'verbose_name': 'Historia clínica', 'verbose_name_plural': 'Historias clínicas'},
        ),
        migrations.RemoveIndex(
            model_name='historiaclinica',
            name='historias_h_pacient_e81da0_idx',
        ),
        migrations.RemoveIndex(
            model_name='historiaclinica',
            name='historias_h_odontol_aaa048_idx',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='bloqueada_para_edicion',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='borrador',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='fecha_hora_atencion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='finalizada_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='finalizada_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historias_clinicas_finalizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='migrada_desde_legacy',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='numero_asiento',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinicaadjunto',
            name='sha256',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='accesoclinicoauditoria',
            name='accion',
            field=models.CharField(choices=[('ver_paciente', 'Ver paciente'), ('ver_historia', 'Ver historia clínica'), ('ver_detalle_historia', 'Ver detalle de historia'), ('crear_historia', 'Crear historia clínica'), ('editar_historia', 'Editar historia clínica'), ('crear_borrador', 'Crear borrador clínico'), ('editar_borrador', 'Editar borrador clínico'), ('crear_version', 'Crear versión clínica'), ('finalizar_historia', 'Finalizar historia clínica'), ('ver_version', 'Ver versión clínica'), ('crear_enmienda', 'Crear enmienda clínica'), ('ver_enmienda', 'Ver enmienda clínica'), ('exportar_historia', 'Exportar historia clínica'), ('verificar_integridad', 'Verificar integridad clínica'), ('intento_editar_finalizada', 'Intentar editar historia finalizada'), ('intento_eliminar_historia', 'Intentar eliminar historia clínica'), ('abrir_adjunto', 'Abrir adjunto clínico'), ('ver_ficha', 'Ver ficha odontológica'), ('editar_ficha', 'Editar ficha odontológica'), ('ver_odontograma', 'Ver odontograma'), ('editar_odontograma', 'Editar odontograma'), ('iniciar_emergencia', 'Iniciar acceso de emergencia'), ('finalizar_emergencia', 'Finalizar acceso de emergencia'), ('archivar_paciente', 'Archivar paciente'), ('reactivar_paciente', 'Reactivar paciente'), ('solicitud_publica_paciente_archivado', 'Solicitud pública de paciente archivado'), ('otp_paciente_archivado', 'OTP solicitado para paciente archivado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='accesoclinicoauditoria',
            name='politica',
            field=models.CharField(blank=True, choices=[('asociacion_activa', 'Asociación activa'), ('compartido', 'Datos compartidos'), ('emergencia', 'Emergencia'), ('administrativa', 'Administrativa'), ('sistema', 'Sistema'), ('sin_permiso', 'Sin permiso'), ('paciente_archivado', 'Paciente archivado')], max_length=40),
        ),
        migrations.AlterField(
            model_name='historiaclinicaadjunto',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos', to='historias.historiaclinica'),
        ),
        migrations.AddIndex(
            model_name='historiaclinica',
            index=models.Index(fields=['paciente', '-numero_asiento'], name='historias_h_pacient_e471ed_idx'),
        ),
        migrations.AddIndex(
            model_name='historiaclinica',
            index=models.Index(fields=['paciente', '-fecha_hora_atencion'], name='historias_h_pacient_ddc252_idx'),
        ),
        migrations.AddIndex(
            model_name='historiaclinica',
            index=models.Index(fields=['odontologo', '-fecha_hora_atencion'], name='historias_h_odontol_534d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='historiaclinica',
            index=models.Index(fields=['borrador', 'bloqueada_para_edicion'], name='historias_h_borrado_71d1e5_idx'),
        ),
        migrations.AddIndex(
            model_name='historiaclinicaadjunto',
            index=models.Index(fields=['sha256'], name='historias_h_sha256_4bc328_idx'),
        ),
        migrations.AddConstraint(
            model_name='historiaclinica',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_asiento__isnull', False)), fields=('paciente', 'numero_asiento'), name='historias_folio_unico_por_paciente'),
        ),
        migrations.AddConstraint(
            model_name='historiaclinica',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('bloqueada_para_edicion', False), ('borrador', True), ('finalizada_en__isnull', True), ('finalizada_por__isnull', True), ('migrada_desde_legacy', False), ('numero_asiento__isnull', True)), models.Q(('bloqueada_para_edicion', True), ('borrador', False), ('finalizada_en__isnull', False), ('finalizada_por__isnull', False), ('migrada_desde_legacy', False), ('numero_asiento__isnull', False)), models.Q(('bloqueada_para_edicion', True), ('borrador', False), ('finalizada_en__isnull', False), ('migrada_desde_legacy', True), ('numero_asiento__isnull', False)), _connector='OR'), name='historias_estado_clinico_coherente'),
        ),
        migrations.AddField(
            model_name='historiaclinicaenmienda',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enmiendas_historia_clinica_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiaclinicaenmienda',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enmiendas', to='historias.historiaclinica'),
        ),
        migrations.AddField(
            model_name='historiaclinicaenmienda',
            name='odontologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enmiendas_historia_clinica', to='turnos.odontologo'),
        ),
        migrations.AddField(
            model_name='historiaclinicaversion',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones_historia_clinica_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiaclinicaversion',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones', to='historias.historiaclinica'),
        ),
        migrations.AddIndex(
            model_name='historiaclinicaenmienda',
            index=models.Index(fields=['historia', 'numero_enmienda'], name='historias_h_histori_3e6e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='historiaclinicaenmienda',
            index=models.Index(fields=['creado_en'], name='historias_h_creado__4048be_idx'),
        ),
        migrations.AddConstraint(
            model_name='historiaclinicaenmienda',
            constraint=models.UniqueConstraint(fields=('historia', 'numero_enmienda'), name='historias_enmienda_unica_por_asiento'),
        ),
        migrations.AddConstraint(
            model_name='historiaclinicaenmienda',
            constraint=models.CheckConstraint(condition=models.Q(('numero_enmienda__gt', 0)), name='historias_enmienda_numero_positivo'),
        ),
        migrations.AddIndex(
            model_name='historiaclinicaversion',
            index=models.Index(fields=['historia', 'numero_version'], name='historias_h_histori_304810_idx'),
        ),
        migrations.AddIndex(
            model_name='historiaclinicaversion',
            index=models.Index(fields=['creado_en'], name='historias_h_creado__18ebf4_idx'),
        ),
        migrations.AddConstraint(
            model_name='historiaclinicaversion',
            constraint=models.UniqueConstraint(fields=('historia', 'numero_version'), name='historias_version_unica_por_asiento'),
        ),
        migrations.AddConstraint(
            model_name='historiaclinicaversion',
            constraint=models.CheckConstraint(condition=models.Q(('numero_version__gt', 0)), name='historias_version_numero_positivo'),
        ),
    ]
