# Generated by Django 6.0.6 on 2026-07-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0007_protecciones_postgresql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesoclinicoauditoria',
            name='accion',
            field=models.CharField(choices=[('ver_paciente', 'Ver paciente'), ('ver_historia', 'Ver historia clínica'), ('ver_detalle_historia', 'Ver detalle de historia'), ('crear_historia', 'Crear historia clínica'), ('editar_historia', 'Editar historia clínica'), ('crear_borrador', 'Crear borrador clínico'), ('editar_borrador', 'Editar borrador clínico'), ('crear_version', 'Crear versión clínica'), ('finalizar_historia', 'Finalizar historia clínica'), ('ver_version', 'Ver versión clínica'), ('crear_enmienda', 'Crear enmienda clínica'), ('ver_enmienda', 'Ver enmienda clínica'), ('exportar_historia', 'Exportar historia clínica'), ('verificar_integridad', 'Verificar integridad clínica'), ('intento_editar_finalizada', 'Intentar editar historia finalizada'), ('intento_eliminar_historia', 'Intentar eliminar historia clínica'), ('abrir_adjunto', 'Abrir adjunto clínico'), ('ver_ficha', 'Ver ficha odontológica'), ('editar_ficha', 'Editar ficha odontológica'), ('ver_odontograma', 'Ver odontograma'), ('editar_odontograma', 'Editar odontograma'), ('iniciar_emergencia', 'Iniciar acceso de emergencia'), ('finalizar_emergencia', 'Finalizar acceso de emergencia'), ('archivar_paciente', 'Archivar paciente'), ('reactivar_paciente', 'Reactivar paciente'), ('solicitud_publica_paciente_archivado', 'Solicitud pública de paciente archivado'), ('otp_paciente_archivado', 'OTP solicitado para paciente archivado'), ('crear_borrador_indicacion', 'Crear borrador de indicación'), ('editar_borrador_indicacion', 'Editar borrador de indicación'), ('ver_indicacion', 'Ver indicación'), ('emitir_indicacion', 'Emitir indicación'), ('generar_pdf_indicacion', 'Generar PDF de indicación'), ('descargar_pdf_indicacion', 'Descargar PDF de indicación'), ('enviar_email_indicacion', 'Enviar indicación por email'), ('error_email_indicacion', 'Error de email de indicación'), ('reenviar_email_indicacion', 'Reenviar indicación por email'), ('anular_indicacion', 'Anular indicación'), ('crear_reemplazo_indicacion', 'Crear reemplazo de indicación'), ('intento_editar_indicacion_emitida', 'Intentar editar indicación emitida'), ('intento_acceso_indicacion', 'Intentar acceder a indicación')], max_length=50),
        ),
    ]
