# Generated by Django 6.0.4 on 2026-05-13 06:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0004_pacienteodontologo'),
        ('turnos', '0008_alter_disponibilidadodontologo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones_generales', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odontograma', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Odontograma',
                'verbose_name_plural': 'Odontogramas',
                'ordering': ['paciente__apellido', 'paciente__nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoDental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diente', models.PositiveSmallIntegerField()),
                ('cara', models.CharField(choices=[('vestibular', 'Vestibular'), ('lingual_palatina', 'Lingual / palatina'), ('mesial', 'Mesial'), ('distal', 'Distal'), ('oclusal_incisal', 'Oclusal / incisal')], max_length=30)),
                ('estado_clinico', models.CharField(choices=[('sano', 'Sano'), ('caries', 'Caries'), ('restauracion_necesaria', 'Restauración necesaria'), ('extraccion_indicada', 'Extracción indicada'), ('obturacion', 'Obturación'), ('corona', 'Corona'), ('implante', 'Implante'), ('conducto', 'Conducto'), ('fractura', 'Fractura'), ('sellador', 'Sellador'), ('protesis', 'Prótesis'), ('temporal', 'Temporal'), ('control', 'Control'), ('ausente', 'Ausente'), ('extraido', 'Extraído'), ('observacion_especial', 'Observación especial')], max_length=40)),
                ('color', models.CharField(choices=[('azul', 'Azul'), ('rojo', 'Rojo'), ('verde', 'Verde'), ('negro', 'Negro'), ('neutro', 'Sin color')], default='neutro', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('realizado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('odontologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estados_dentales_registrados', to='turnos.odontologo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estados_dentales_registrados', to=settings.AUTH_USER_MODEL)),
                ('odontograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_dentales', to='odontogramas.odontograma')),
            ],
            options={
                'verbose_name': 'Estado dental',
                'verbose_name_plural': 'Estados dentales',
                'ordering': ['-fecha', '-creado_en'],
                'indexes': [models.Index(fields=['odontograma', 'diente', 'cara', 'activo'], name='odontograma_odontog_c6183f_idx'), models.Index(fields=['odontograma', 'fecha'], name='odontograma_odontog_9a69f1_idx'), models.Index(fields=['odontologo', 'fecha'], name='odontograma_odontol_baa429_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('odontograma', 'diente', 'cara'), name='uniq_estado_dental_activo_por_cara')],
            },
        ),
    ]
