# Generated by Django 6.0.4 on 2026-05-13 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0003_alter_historiaclinica_options_and_more'),
        ('odontogramas', '0001_initial'),
        ('turnos', '0008_alter_disponibilidadodontologo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estadodental',
            name='historia_clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estados_dentales', to='historias.historiaclinica'),
        ),
        migrations.AddIndex(
            model_name='estadodental',
            index=models.Index(fields=['historia_clinica', '-creado_en'], name='odontograma_histori_84f799_idx'),
        ),
    ]
